# Generated by Django 4.1.3 on 2022-11-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriamanutencao',
            options={'verbose_name': 'Categoria da Manutenção', 'verbose_name_plural': 'Categoria das Manutenções'},
        ),
        migrations.AlterField(
            model_name='servico',
            name='protocole',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
